services:

  mysql:
    image: mysql:8
    container_name: mysql-credit
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
    ports:
      - "3307:3306"

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow-webserver
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://root:root@mysql/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow-scheduler
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://root:root@mysql/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler

  credit-pipeline:
    build: .
    container_name: credit-pipeline
    depends_on:
      - mysql